[package]
name = "user_lib"
version = "0.1.0"
authors = ["yangpan"]
edition = "2018"

[dependencies]
buddy_system_allocator = "0.6"
riscv = { git = "https://github.com/rcore-os/riscv", features = ["inline-asm"] }
spin = "0.7.0"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }